[package]
name = "restarter"
version = "0.1.0"
edition = "2021"

[dependencies.anyhow]
workspace = true

[dependencies.k8s-openapi]
version = "0.18.0"
features = ["v1_26"]

[dependencies.kube]
version = "0.84.0"

[dependencies.time]
workspace = true

[dependencies.tokio]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.tracing-subscriber]
workspace = true

[dependencies.serenity]
workspace = true
