[package]
name = "restarter"
version = "0.1.1"
edition = "2021"

[dependencies.anyhow]
workspace = true

[dependencies.k8s-openapi]
version = "0.19.0"
features = ["v1_27"]

[dependencies.kube]
version = "0.85.0"

[dependencies.logging]
workspace = true

[dependencies.tokio]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.serenity]
workspace = true
