[package]
name = "seitai"
version = "0.1.24"
edition = "2021"

[dependencies.anyhow]
workspace = true

[dependencies.futures]
version = "0.3.31"

[dependencies.hashbrown]
version = "0.15.2"

[dependencies.http-body-util]
workspace = true

[dependencies.hyper]
workspace = true

[dependencies.hyper-util]
workspace = true

[dependencies.indexmap]
version = "2.7.0"
features = ["serde"]

[dependencies.lazy-regex]
version = "3.3.0"
features = ["lite"]

[dependencies.logging]
workspace = true

[dependencies.ordered-float]
version = "4.5.0"

[dependencies.regex-lite]
version = "0.1.6"

[dependencies.sea-query]
version = "0.32.1"
default-features = false
features = ["backend-postgres", "derive", "thread-safe"]

[dependencies.sea-query-binder]
version = "0.7.0"
features = ["sqlx-postgres"]

[dependencies.serde]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.serenity]
workspace = true
features = ["builder", "collector"]

[dependencies.songbird]
version = "0.4.6"
features = ["builtin-queue"]

[dependencies.sqlx]
version = "0.8.2"
features = ["postgres", "runtime-tokio", "tls-native-tls"]

[dependencies.strum]
features = ["derive"]
version = "0.26.3"

[dependencies.symphonia]
version = "0.5.4"
features = ["wav"]

[dependencies.tokio]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.url]
workspace = true

[dependencies.uuid]
workspace = true

[dependencies.voicevox]
path = "../crates/voicevox"

[dev-dependencies.mockall]
version = "0.13.1"
