[package]
name = "seitai"
version = "0.1.12"
edition = "2021"

[dependencies.anyhow]
workspace = true

[dependencies.hashbrown]
version = "0.14.0"

[dependencies.indexmap]
version = "2.0.0"
features = ["serde"]

[dependencies.lazy-regex]
version = "3.0.1"
features = ["lite"]

[dependencies.logging]
workspace = true

[dependencies.regex-lite]
version = "0.1.0"

[dependencies.serenity]
workspace = true
features = ["builder", "collector"]

[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird.git"
branch = "next"
features = ["builtin-queue"]

[dependencies.symphonia]
version = "0.5.2"
features = ["wav"]

[dependencies.tokio]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.uuid]
workspace = true

[dependencies.voicevox]
path = "../crates/voicevox"
