[package]
name = "logging"
version = "0.0.0"
edition = "2024"

[lib]
doctest = false

[dependencies.time]
version = "0.3.45"
features = ["macros"]

[dependencies.tracing-subscriber]
version = "0.3.22"
features = ["env-filter", "time"]
