[package]
name = "logging"
version = "0.0.0"
edition = "2021"

[dependencies.time]
version = "0.3.25"
features = ["macros"]

[dependencies.tracing-subscriber]
version = "0.3.17"
features = ["env-filter", "time"]
